apiVersion: v1
kind: Namespace
metadata:
        name: mynamespace
        labels:
                name: mynamespace
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
        name: basicwebservice
        namespace: mynamespace
        labels:
                aadpodidbinding: basicwebservice-selector
spec:
        replicas: 1
        template:
                metadata:
                        labels:
                                app: basicwebservice
                                aadpodidbinding: basicwebservice-selector
                spec:
                        nodeSelector:
                                "beta.kubernetes.io/os": linux
                        containers:
                                - name: basicwebservice
                                  image: myacrregistry.azurecr.io/basicwebservice:v1.0
                                  volumeMounts:
                                          - name: kvsecretvolume
                                            mountPath: /kvmnt
                                            readOnly: true
                                  ports:
                                          - containerPort: 80
                        volumes:
                                - name: kvsecretvolume
                                  flexVolume:
                                          driver: "azure/kv"
                                          options:
                                                  usepodidentity: "true"
                                                  keyvaultname: "bhkhkeyvault1"
                                                  keyvaultobjectnames: "testsecret;bhaskarsignercertificate;"
                                                  keyvaultobjecttypes: "secret;secret;"
                                                  keyvaultobjectversions: ""
                                                  resourcegroup: "<resource group>"
                                                  subscriptionid: "<subscription id>"
                                                  tenantid: "72f988bf-86f1-41af-91ab-2d7cd011db47"

---
apiVersion: v1
kind: Service
metadata:
        name: basicwebservice
        namespace: mynamespace
spec:
        type: LoadBalancer
        ports:
                - port: 80
        selector:
                app: basicwebservice
