apiVersion: apps/v1beta1
kind: Deployment
metadata:
        name: basicwebservice
spec:
        replicas: 1
        strategy:
                rollingUpdate:
                        maxSurge: 1
                        maxUnavailable: 1
        minReadySeconds: 20
        template:
                metadata:
                        labels:
                                app: basicwebservice
                spec:
                        nodeSelector:
                                "beta.kubernetes.io/os": linux
                        containers:
                        - name: basicwebservice
                          image: substrated2registry.azurecr.io/basicwebservice:v4.1
                          volumeMounts:
                          - name: kvsecretvolume
                            mountPath: /kvmnt
                            readOnly: true
                          ports:
                          - containerPort: 80
                        volumes:
                        - name: kvsecretvolume
                          flexVolume:
                                  driver: "azure/kv"
                                  secretRef:
                                          name: kvcreds
                                  options:
                                          usepodidentity: "false"
                                          keyvaultname: "bhkhkeyvault1"
                                          keyvaultobjectnames: "testsecret;bhaskarsignercertificate;testselfsignedcert"
                                          keyvaultobjecttypes: "secret;secret;secret"
                                          keyvaultobjectversions: ""
                                          resourcegroup: "testrgbh"
                                          subscriptionid: "2ca5368d-58c7-49b4-9459-6dac3c542d06"
                                          tenantid: "72f988bf-86f1-41af-91ab-2d7cd011db47"

---
apiVersion: v1
kind: Service
metadata:
        name: basicwebservice
spec:
        type: LoadBalancer
        ports:
        - port: 80
        selector:
                app: basicwebservice




